- hosts: tag_AnsibleGroup_apps
  gather_facts: false
  vars:
  - ansible_remote_tmp: /tmp/.ansible
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"

  - name: Debug Var
    debug:
      var: ansible_remote_tmp
