---
# tasks file for base-config
- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: Remove internal repositories from ec2 machines
  file:
    path: '/etc/yum.repos.d/internal.repo'
    state: absent
  tags: ec2

- name: Copy repo file to destination server 
  copy:
    src: files/open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    owner: root
    group: root
    mode: 0644
  register: copyresult

- name: Run Copy Report
  debug:
    var: copyresult

- name: enable repos
  file:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Clearing yum cache
  command: yum clean all

#- name: setup hostname
#  hostname:
#    name: "{{ inventory_hostname }}"
 
- name: install base tools and packages
  yum:
    name:
      - httpie
      - python-pip
    state: latest
